Repository AY2425S1-CS2103T-F12-3/tp, pull requests merged in 2024-10, with the labels that each got.

#57 Add new patient parameters and modify classes to support new parameters
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#64 Add Priority Class
  src/main/java/seedu/address/model/person/Priority.java
  src/test/java/seedu/address/model/person/PriorityTest.java
Labels: type.Task, priority.High

#74 Implement PriorityCommandParser class and PriorityCommand class
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PriorityCommandParser.java
  src/main/java/seedu/address/model/person/Priority.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PriorityCommandTest.java
  src/test/java/seedu/address/logic/parser/PriorityCommandParserTest.java
Labels: type.Task, priority.High

#82 Integrate Priority into Person Class to enable support for Priority
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PriorityCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Priority.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/PriorityCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PriorityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.High

#92 Update DeleteCommand to accept NRIC instead of Index
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/NricTest.java
Labels: type.Enhancement, type.Task, priority.Medium

#93 Rename COMMAND_WORD from updatePriority to assignPriority
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
Labels: type.Task, priority.Medium, severity.VeryLow

#87 Add MedCon command
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddMedConCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMedConCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/MedCon.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddMedConCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddMedConCommandParserTest.java
  src/test/java/seedu/address/model/person/MedConTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, type.Task, priority.High

#94 Update test cases for edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.Medium

#97 Add ability to add multiple medical conditions
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddMedConCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMedConCommandParser.java
  src/main/java/seedu/address/model/person/MedCon.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMedCon.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddMedConCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddMedConCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMedConTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement, priority.Medium

#100 Make MedCon and Tag comparable
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddMedConCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/MedCon.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/MedConTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#103 Add `findMedCon` command to find patients base on their medical conditions
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindMedConCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindMedConCommandParser.java
  src/main/java/seedu/address/model/person/MedConContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/FindMedConCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindMedConCommandParserTest.java
  src/test/java/seedu/address/model/person/MedConContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#108 Implement ListPrioCommand Class and PriorityMatchesPredicate
  src/main/java/seedu/address/logic/commands/ListPrioCommand.java
  src/main/java/seedu/address/model/person/PriorityMatchesPredicate.java
  src/test/java/seedu/address/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteApptCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPrioCommandTest.java
  src/test/java/seedu/address/model/person/PriorityMatchesPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#111 Add colours to priority in GUI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/styles.css
Labels: type.Enhancement, type.Task, priority.Medium

#120 Bug Fix where Priority is not shown due to background color in GUI
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Task, type.Bug, priority.Medium, severity.Medium

#122 Bug Fix for potentially Multiple Parameter in PriorityCommandParser
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/PriorityCommandParser.java
  src/test/java/seedu/address/logic/parser/PriorityCommandParserTest.java
Labels: type.Task, type.Bug, priority.Medium, severity.Medium

#123 Duplication Guard for AddApptCommandParser and DelApptCommandParser
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java
  src/test/java/seedu/address/logic/parser/AddApptCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteApptCommandParserTest.java
Labels: type.Bug, priority.High, severity.High

#119 Add missing find nric feature
  src/main/java/seedu/address/logic/parser/AddAllergyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Bug, priority.Medium

#124 Add ListPrioCommandParser and test cases
  src/main/java/seedu/address/logic/commands/ListPrioCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListPrioCommandParser.java
  src/test/java/seedu/address/logic/parser/ListPrioCommandParserTest.java
Labels: type.Task, priority.High

#110 Rename tags to allergies
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAllergyCommand.java
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddMedConCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddAllergyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/allergy/Allergy.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAllergyCommandTest.java
  src/test/java/seedu/address/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteApptCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddAllergyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/allergy/AllergyTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#129 Amend generateSuccessMessage from name to Nric
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
Labels: type.Enhancement, priority.Low

#131 Update success message for addMedCon and delMedCon
  src/main/java/seedu/address/logic/commands/AddMedConCommand.java
  src/main/java/seedu/address/logic/commands/DelMedConCommand.java
Labels: priority.Low, severity.Low

#135 Bug Fix for Priority being unable to be assigned when person not in view
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
Labels: type.Task, type.Bug, priority.High, severity.Medium

#140 Fix string formatting issues
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FindMedConCommand.java
Labels: type.Bug, priority.Medium, severity.Low

#138 Fix bug in add allergy
  src/main/java/seedu/address/logic/commands/AddAllergyCommand.java
Labels: type.Bug, priority.Medium, severity.Medium

#146 Rename 'AddressBook' and 'Address App' to MediBase3
  build.gradle
  src/main/resources/view/MainWindow.fxml
Labels: severity.VeryLow

#148 Reorder GUI elements to better display patient details
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/styles.css
Labels: type.Task, priority.Medium, severity.Medium

#151 Rename Priority Command's command word from assignPriority to setPriority
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
Labels: type.Enhancement, type.Task, priority.Low

#152 Refactor and Enhance Medical Condition Commands and Parsers
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddMedConCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DelMedConCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/MedCon.java
  src/main/java/seedu/address/storage/JsonAdaptedMedCon.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddMedConCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DelMedConCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMedConTest.java
Labels: priority.Low, severity.Low

#157 Change error message for Delete and FindNRIC command
  build.gradle
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindNricCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.Low

#160 Limit appt length
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddApptCommandParserTest.java
Labels: type.Bug, priority.High, severity.Medium

#163 Add history
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: type.Enhancement, priority.Low

#161 Tweak UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddAllergyCommand.java
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/parser/AddAllergyCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/OwnedAppointment.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/AppointmentListPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/AppointmentListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/styles.css
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task, priority.High, priority.Medium

#171 Fix CSS bug for Allergy tag
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, priority.Low, severity.VeryLow

#168 Update `add` feature description in UG and add Parameter Details
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: type.Task, priority.Low, type.UserGuide

#167 Update the FAQ in UG
  docs/UserGuide.md
Labels: type.Task, priority.Low, type.UserGuide

#172 Update Ui and logic UML diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: priority.Medium, type.DeveloperGuide

#178 Update `find` commands in the user guide
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonMediBase3StorageTest/invalidAndValidPersonMediBase3.json
  src/test/data/JsonMediBase3StorageTest/invalidPersonMediBase3.json
  src/test/data/JsonMediBase3StorageTest/notJsonFormatMediBase3.json
  src/test/data/JsonSerializableMediBase3Test/duplicatePersonMediBase3.json
  src/test/data/JsonSerializableMediBase3Test/invalidPersonMediBase3.json
  src/test/data/JsonSerializableMediBase3Test/typicalPersonsMediBase3.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.Medium, type.UserGuide

#184 Update features under Managing Patient section of UG
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: type.Task, priority.Medium, type.UserGuide

#182 Update undo sequence diagram model in developer guide
  docs/diagrams/UndoSequenceDiagram-Model.puml
Labels: priority.Medium, type.UserGuide

#185 Remove tag from project
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/storage/JsonAdaptedAllergy.java
  src/main/java/seedu/address/storage/JsonAdaptedMedCon.java
  src/test/java/seedu/address/logic/commands/AddAllergyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/allergy/AllergyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: type.Bug, priority.High, severity.Medium

#186 Add 'How to use User Guide' section and fix formatting issues
  docs/UserGuide.md
Labels: priority.Medium, severity.VeryLow, type.UserGuide

#191 Update Feature List and Parameter Details
  docs/UserGuide.md
Labels: priority.Medium, type.UserGuide

#195 Update Feature List for Priority Feature
  docs/UserGuide.md
Labels: priority.Medium, type.UserGuide

#193 Update add allergy in the user guide
  docs/UserGuide.md
Labels: priority.Medium, type.UserGuide

#194 Update Developer Guide's Model diagram
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/img.png
Labels: priority.Medium, type.DeveloperGuide

#200 Remove file accidentally generated during uml diagram generation
  docs/img.png
Labels: priority.Low, severity.VeryLow, type.DeveloperGuide

#197 Add Quick Start to UG
  docs/UserGuide.md
  docs/images/CommandPromptFormat.jpg
  docs/images/GUIOverview.jpg
  docs/images/githubAssets.png
  docs/images/javaVersionLinux.jpg
  docs/images/javaVersionMacOS.png
  docs/images/javaVersionWindows.jpeg
Labels: priority.High, severity.High, type.UserGuide

#204 Fix header formatting in QuickStart
  docs/UserGuide.md
Labels: priority.Low, severity.Low

#206 Update Sequence diagram for Delete
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: priority.Medium, severity.Medium, type.DeveloperGuide

#208 Update delete allergy in the user guide
  docs/UserGuide.md
Labels: priority.Low, type.UserGuide

#199 Adjust cosmetics and formatting of UG
  docs/UserGuide.md
Labels: priority.Medium, type.UserGuide

#202 Add appointment management to UG
  docs/UserGuide.md
Labels: priority.High, severity.High, type.UserGuide

#210 Refactor DateUtil and fix being able to add invalid dates
  docs/team/hweinian.md
  docs/team/presleychew.md
  docs/team/techraj.md
  docs/team/yadobler.md
  docs/team/yong-zhuo.md
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/test/data/JsonMediBase3StorageTest/invalidAndValidPersonMediBase3.json
  src/test/data/JsonSerializableMediBase3Test/duplicatePersonMediBase3.json
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: priority.Medium

#212 Update Developer Guide's UML Storage Class Diagram
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: priority.High, type.DeveloperGuide

#218 Amend UserGuide's Introduction
  docs/UserGuide.md
Labels: priority.Medium, type.UserGuide

#217 Add setPriority in Command Summary of User Guide
  docs/UserGuide.md
Labels: priority.High, type.UserGuide

#225 Bug: Able to add duplicate allergies
  src/main/java/seedu/address/model/person/Allergy.java
Labels: type.Task, priority.Medium, severity.Low, alpha-bug

#235 Bug: Error message showing wrong usage for edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: severity.Low, alpha-bug

#224 Add Appointment Management Feature in User Guide
  docs/UserGuide.md
Labels: priority.High, type.UserGuide

#240 Amend MESSAGE_USAGE of setPriority Command to ensure consistency
  src/main/java/seedu/address/logic/commands/PriorityCommand.java
Labels: type.Task, priority.Medium, severity.Low, alpha-bug

#244 Add more specific error message for invalid DateOfBirth
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Nric.java
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, severity.Low

#247 Rename PriorityCommandClass to SetPriorityCommand for consistency
  src/main/java/seedu/address/logic/commands/SetPriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SetPriorityCommandParser.java
  src/test/java/seedu/address/logic/commands/SetPriorityCommandTest.java
  src/test/java/seedu/address/logic/parser/SetSetPriorityCommandParserTest.java
Labels: type.Enhancement, type.Task, priority.Medium

#245 Fix invalid command format messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Bug, severity.Low

#246 Fix UG bug
  docs/UserGuide.md
Labels: type.Bug, severity.Low, type.UserGuide

#248 Update NFR and Glossary and Testing Instructions
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low, type.DeveloperGuide

#254 Bug: Able to add duplicate medical conditions
  src/main/java/seedu/address/model/person/MedCon.java
  src/test/java/seedu/address/storage/JsonAdaptedMedConTest.java
Labels: priority.High, severity.High, alpha-bug

#255 Bug: Non-standardised error messages for medical condition and allergy commands
  src/main/java/seedu/address/logic/commands/AddAllergyCommand.java
  src/main/java/seedu/address/logic/commands/AddMedConCommand.java
  src/main/java/seedu/address/logic/commands/DelAllergyCommand.java
  src/main/java/seedu/address/logic/commands/DelMedConCommand.java
Labels: priority.Low, severity.Low, alpha-bug

#252 Update the DG use case
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, type.DeveloperGuide

#263 Amend phrasing in Priority feature's Use cases in DG
  docs/DeveloperGuide.md
Labels: priority.Medium, type.DeveloperGuide

#256 Bug: Unspecific error messages for MedCon and Allergy commands when input is not alphanumeric
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAllergyCommand.java
  src/main/java/seedu/address/logic/commands/AddMedConCommand.java
  src/main/java/seedu/address/logic/commands/DelAllergyCommand.java
  src/main/java/seedu/address/logic/commands/DelMedConCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.Low, severity.Low, alpha-bug

#258 Refactor Quick Start - Shift JDK17 Instructions to FAQ and Update Code Formatting for PDF Compatibility
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.UserGuide

#268 Fix UG Formatting
  docs/UserGuide.md
Labels: priority.Low, severity.Low, type.UserGuide

#269 UG: fix glossary table formatting issue
  docs/UserGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, severity.Medium, type.UserGuide, alpha-bug

#271 Fix UG Formatting for TOC
  docs/UserGuide.md
Labels: priority.Low, severity.Low, type.UserGuide

#272 UG: fix missing panel documentation
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.UserGuide, alpha-bug

#273 AddAppt error message now specifies if date with correct format is invalid
  src/main/java/seedu/address/model/appointment/Appointment.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#282 Update DG Appendix with add/del MedCon and delAllergy
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Low, type.DeveloperGuide

#275 Update appendix instruction for manual testing (listPrio and setPriority)
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, type.DeveloperGuide

#284 Update appendix in the user guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, type.DeveloperGuide

#285 Amend MESSAGEs in the various command classes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
Labels: type.Task, priority.High, severity.Low, alpha-bug

#286 Amend User Stories in DG
  docs/DeveloperGuide.md
Labels: type.Story, type.Task, priority.High, type.DeveloperGuide

#291 Update sampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low, severity.Low

#294 Bug Fix: Misleading Error Message for Invalid NRIC Input #276
  src/main/java/seedu/address/model/person/Nric.java
Labels: priority.Low, severity.Low, alpha-bug

#293 Fix incorrect variable naming
  src/main/java/seedu/address/model/appointment/Appointment.java
Labels: type.Bug, priority.High, severity.High
